export default {
  GET_PATH: "get-path",
  INIT_ROLLBAR: "init-rollbar",
  IOT_CONNECT: "iot-connect",
  IOT_ERROR: "iot-error",
  IOT_MESSAGE: "iot-message",
  MANUAL_UPDATE_MODAL: "manual-update-modal",
  SET_FORCE_QUIT: "set-force-quit",
  SHOW_ABOUT_MODAL: "show-about-modal",
  SHOW_SETTINGS_MODAL: "show-settings-modal",
  SHOW_UPDATE_MODAL: "show-update-modal",
  SHOW_WINDOW: "show-window",
  START_IOT: "start-iot",
  STORAGE_GET: "storage-get",
  STORAGE_SET: "storage-set",
  UPDATE_TURNS_AVAILABLE: "update-turns-available",
};
